package prism.util;

public class Instructions {
    public static final int NULL = -0x1;
    public static final int FALSE = 0x0;
    public static final int TRUE = 0x1;
    public static final int PING = 0x2;
    public static final int LOGIN = 0x3;
    public static final int WRITE = 0x4;
    public static final int READ = 0x5;
    public static final int REPLY = 0x6;
    public static final int TIME = 0x7;
    public static final int REGISTER = 0x8;
    public static final int MESSAGE = 0x9;
    public static final int STATUS = 0xA;
    public static final int SET_STATUS = 0xB;
    public static final int GET_STATUS = 0xC;
    public static final int USERNAME = 0xD;
    public static final int PASSWORD = 0xE;
    public static final int AUTH_KEY = 0xF;
    public static final int OTHER = 0x10;
    public static final int NAME = 0x11;
    public static final int FAILURE = 0x12;
    public static final int SUCCESS = 0x13;
    public static final int INVALID = 0x14;
    public static final int NOT_FOUND = 0x15;
    public static final int DEFAULT = 0x16;
    public static final int RESTRICTED = 0x17;
    public static final int ERROR = 0x18;
    public static final int COUNT = 0x19;
    public static final int NUMBER = 0x1A;
    public static final int ARRAY = 0x1B;
    public static final int STRING = 0x1C;
    public static final int DATA = 0x1D;
    public static final int AUTHOR = 0x1E;
    public static final int SELF_KEY = 0x1F;
    public static final int SELF_KEY_ENCRYPTED = 0x20;
    public static final int CREATE_CONVERSATION = 0x21;
    public static final int ADD_PARTICIPANT = 0x22;
    public static final int REMOVE_PARTICIPANT = 0x23;
    public static final int TYPE = 0x24;
    public static final int GET = 0x25;
    public static final int USERS = 0x26;
}
